services:
  ics-iqbert-redis:
    ports:
      - 6379:6379

  ics-iqbert-worker:
    volumes:
      - ./ics:/app/ics
      - ./lib:/app/lib

  ics-iqbert-backend:
    volumes:
      - ./ics:/app/ics
      - ./lib:/app/lib
    command: uvicorn ics_components.main:app --port 9996 --reload --app-dir src --host 0.0.0.0
    ports:
      - 9899:9899 # python debug server
      - 9996:9996

  ics-iqbert-rq-dashboard:
    image: ${REGISTRY_PATH}ics-iqbert-worker
    container_name: ics-iqbert-rq-dashboard
    build:
      dockerfile: worker.Dockerfile
    command: rq-dashboard --redis-url=redis://ics-iqbert-redis:6379
    ports:
      - 9182:9182




