services:
  ics-iqbert-redis:
    container_name: ics-iqbert-redis
    image: redis:7.4-bookworm
    command:
      - "bash"
      - "-c"
      - "redis-server --maxmemory 1073741824 --maxmemory-policy volatile-lru"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  ics-iqbert-worker:
    image: ${REGISTRY_PATH}ics-iqbert-worker
    build:
      dockerfile: worker.Dockerfile
    volumes:
      - ics-iqbert-data:/data
    command: rq worker -u redis://ics-iqbert-redis:6379 default
    environment:
      REDIS_HOST: ics-iqbert-redis
      IS_DATA_DIR: /data
    deploy:
      replicas: 3
    depends_on:
      ics-iqbert-redis:
        condition: service_healthy

  ics-iqbert-backend:
    image: ${REGISTRY_PATH}ics-iqbert-backend
    container_name: ics-iqbert-backend
    build:
      dockerfile: backend.Dockerfile
    volumes:
      - ics-iqbert-data:/data
    command: uvicorn ics_components.main:app --port 9996 --app-dir src --host 0.0.0.0
    environment:
      REDIS_HOST: ics-iqbert-redis
      IS_DATA_DIR: /data

    depends_on:
      - ics-iqbert-redis

volumes:
  ics-iqbert-data:
